const DUMMY_ARTICLES = [
  {
    source: {
      id: null,
      name: 'YouTube',
    },
    author: null,
    title: 'Gonzaga Bulldogs vs. UCLA Bruins | Full Game Highlights - ESPN',
    description: 'No. 1 Gonzaga dominates No. 2 UCLA with a 83-63 victory in Las Vegas. Andrew Nembhard leads the Bulldogs with 24 PTS while freshman Chet Holmgren records 15 ...',
    url: 'https://www.youtube.com/watch?v=ULAPnunL1b8',
    urlToImage: 'https://i.ytimg.com/vi/ULAPnunL1b8/maxresdefault.jpg',
    publishedAt: '2021-11-24T05:29:01Z',
    content: null,
  },
  {
    source: {
      id: 'fox-news',
      name: 'Fox News',
    },
    author: 'Hannah Grossman',
    title: "Donald Trump slams prosecutors' 'misconduct' in Kyle Rittenhouse trial after meeting with teen in Mar-A-Lago - Fox News",
    description: "Former President Donald Trump said he met with Kyle Rittenhouse in Mar-a-Lago and said the teen faced 'prosecutorial misconduct' in the Kenosha trial on \"Hannity\" Tuesday.",
    url: 'https://www.foxnews.com/media/donald-trump-meets-kyle-rittenhouse-prosecutorial-misconduct-kenosha-trial',
    urlToImage: 'https://static.foxnews.com/foxnews.com/content/uploads/2021/11/A-Blo-3.jpg',
    publishedAt: '2021-11-24T05:26:21Z',
    content: 'Former President Donald Trump commented on the trial of Kyle Rittenhouse Tuesday on "Hannity" after meeting with the teen in Mar-A-Lago. \r\nTrump said Rittenhouse was subjected to "prosecutorial misco… [+5100 chars]',
  },
  {
    source: {
      id: null,
      name: 'Cbslocal.com',
    },
    author: 'CBS San Francisco',
    title: '9 Charged In Smash-and-Grab Robberies at Louis Vuitton, Other Stores At San Francisco’s Union Square - CBS San Francisco',
    description: "Nine people are facing a series of felony charges following a smash-and-grab robbery at the Louis Vuitton store in San Francisco's Union Square and at other businesses on Friday.",
    url: 'https://sanfrancisco.cbslocal.com/2021/11/23/smash-and-grab-robbery-looting-louis-vuitton-san-francisco-union-square/',
    urlToImage: 'https://sanfrancisco.cbslocal.com/wp-content/uploads/sites/15116056/2021/11/sfpd-usquare-investigat.jpg?w=1024',
    publishedAt: '2021-11-24T04:30:00Z',
    content: 'SAN FRANCISCO (CBS SF) — Nine people are facing a series of felony charges following a smash-and-grab robbery at the Louis Vuitton store in San Francisco’s Union Square and at other businesses on Fri… [+4078 chars]',
  },
  {
    source: {
      id: null,
      name: 'Fox Business',
    },
    author: 'Associated Press',
    title: 'DOJ asks court to allow OSHA vaccine mandate - Fox Business',
    description: 'The Biden administration on Tuesday asked a federal court to let it move ahead with a workplace rule that would require employees at larger companies to be vaccinated against COVID-19 or face weekly testing.',
    url: 'https://www.foxbusiness.com/politics/biden-doj-asks-court-to-reinstate-osha-vaccine-mandate',
    urlToImage: 'https://a57.foxnews.com/static.foxbusiness.com/foxbusiness.com/content/uploads/2021/11/0/0/GettyImages-1355154411-e1637704581942.jpg?ve=1&tl=1',
    publishedAt: '2021-11-24T04:21:56Z',
    content: 'The Biden administration on Tuesday asked a federal court to let it move ahead with a workplace rule that would require employees at larger companies to be vaccinated against COVID-19 or face weekly … [+3720 chars]',
  },
  {
    source: {
      id: 'the-wall-street-journal',
      name: 'The Wall Street Journal',
    },
    author: 'Kris Maher',
    title: 'Walgreens, Walmart and CVS Pharmacies Contributed to Opioid Epidemic, Ohio Jury Finds - The Wall Street Journal',
    description: 'Two state counties argued pharmacy chains created public nuisance by enabling opioid crisis',
    url: 'https://www.wsj.com/articles/ohio-jury-finds-pharmacies-operated-by-cvs-walgreens-walmart-contributed-to-opioid-epidemic-11637695351',
    urlToImage: 'https://images.wsj.net/im-440256/social',
    publishedAt: '2021-11-24T04:13:00Z',
    content: 'A federal jury in Cleveland on Tuesday found that the companies owning CVS, Walgreens and Walmart pharmacies were liable for contributing to the opioid epidemic in two Ohio countiesthe first, potenti… [+468 chars]',
  },
  {
    source: {
      id: 'reuters',
      name: 'Reuters',
    },
    author: null,
    title: 'New Zealand to reopen to foreign travellers from April 30 - Reuters',
    description: 'New Zealand will keep its borders closed to most international travellers for a further five months, the government said on Wednesday, outlining a cautious easing of border curbs that have been in place since COVID-19 hit in March 2020.',
    url: 'https://www.reuters.com/world/asia-pacific/new-zealand-reopen-foreign-travellers-april-30-2021-11-24/',
    urlToImage: 'https://www.reuters.com/resizer/GqUE96M1hjwxJD3Uk-NyIsdTP58=/1200x628/smart/filters:quality(80)/cloudfront-us-east-2.images.arcpublishing.com/reuters/XQKYANFV2BOYDK4CID742KB2DI.jpg',
    publishedAt: '2021-11-24T03:22:00Z',
    content: 'WELLINGTON, Nov 24 (Reuters) - New Zealand will keep its borders closed to most international travellers for a further five months, the government said on Wednesday, outlining a cautious easing of bo… [+1644 chars]',
  },
  {
    source: {
      id: 'independent',
      name: 'Independent',
    },
    author: 'Megan Sheets',
    title: 'Wisconsin parade news – latest: Darrell Brooks appears in court as prosecutors announce sixth Waukesha victim - The Independent',
    description: 'Follow the latest updates',
    url: 'https://www.independent.co.uk/news/world/americas/crime/wisconsin-waukesha-victim-darrell-brooks-live-b1963284.html',
    urlToImage: 'https://static.independent.co.uk/2021/11/23/17/2021-11-23T155330Z_435044062_RC2A0R96F3VF_RTRMADP_3_WISCONSIN-PARADE.JPG?width=1200&auto=webp&quality=75',
    publishedAt: '2021-11-24T03:02:42Z',
    content: 'Darrell Brooks appears in court following Wisconsin parade attack\r\nDarrell Brooks appeared in court today for a preliminary hearing on charges for allegedly killing six people by ramming his car into… [+8810 chars]',
  },
  {
    source: {
      id: null,
      name: 'The Ringer',
    },
    author: 'Jodi Walker',
    title: '‘The Bachelorette’ Recap: Listen to the Children - The Ringer',
    description: 'Clayton meets Michelle’s students (and the back seat of a departing SUV), Brandon meets the parents, and Nayte once again meets the benefits of being tall',
    url: 'https://www.theringer.com/2021/11/23/22799620/the-bachelorette-season-18-episode-6-recap-brandon-clayton-dumped',
    urlToImage: 'https://cdn.vox-cdn.com/thumbor/r8p9K3DbIZXqBefcuA-XcSaiEJ8=/0x0:1200x628/fit-in/1200x630/cdn.vox-cdn.com/uploads/chorus_asset/file/23039104/BacheloretteMichelleEp06_ABC_Ringer.jpeg',
    publishedAt: '2021-11-24T03:02:03Z',
    content: 'There comes a time in every Bachelorettes journey when she has to look past her boyfriends Johnny Bravo chin, well beyond his 2013 One Direction hair, and even the gleaming rows of orthodontia his pa… [+15764 chars]',
  },
  {
    source: {
      id: null,
      name: 'SciTechDaily',
    },
    author: null,
    title: 'Solar Energy Breakthrough: Ultrathin Solar Cells Using 2D Perovskites Get a Boost - SciTechDaily',
    description: 'Rice lab finds 2D perovskite compound has the right stuff to challenge bulkier products. Rice University engineers have achieved a new benchmark in the design of atomically thin solar cells made of semiconducting perovskites, boosting their efficiency while r…',
    url: 'https://scitechdaily.com/solar-energy-breakthrough-ultrathin-solar-cells-using-2d-perovskites-get-a-boost/',
    urlToImage: 'https://scitechdaily.com/images/2D-Perovskite-Solar-Cell-for-Testing-scaled.jpg',
    publishedAt: '2021-11-24T02:12:46Z',
    content: 'ByRice UniversityNovember 23, 2021\r\nA two-dimensional coat of a perovskite compound is the basis for an efficient solar cell that might stand up to environmental wear and tear, unlike earlier perovsk… [+9225 chars]',
  },
  {
    source: {
      id: null,
      name: 'YouTube',
    },
    author: null,
    title: 'GRAMMY Nominations 2022: Biggest Surprises and Snubs! - Entertainment Tonight',
    description: 'The 64th Annual GRAMMY Awards air Jan. 31 on CBS.',
    url: 'https://www.youtube.com/watch?v=kIT8XNLPx7o',
    urlToImage: 'https://i.ytimg.com/vi/kIT8XNLPx7o/maxresdefault.jpg',
    publishedAt: '2021-11-24T02:00:08Z',
    content: null,
  },
  {
    source: {
      id: null,
      name: 'CBS Sports',
    },
    author: '',
    title: 'College Football Playoff Rankings: Ohio State jumps Alabama, Cincinnati at No. 4 in new top 25 - CBSSports.com',
    description: 'The third-to-last top 25 rankings from the CFP Selection Committee featured a refreshed top four',
    url: 'https://www.cbssports.com/college-football/news/college-football-playoff-rankings-ohio-state-jumps-alabama-cincinnati-at-no-4-in-new-top-25/',
    urlToImage: 'https://sportshub.cbsistatic.com/i/r/2021/11/24/1c9a25ec-774c-499c-be36-0b7dc3b362ec/thumbnail/1200x675/f71ee228b13b8fb1c74235725b39da60/graphic-cfprosu2.png',
    publishedAt: '2021-11-24T01:41:00Z',
    content: 'The fourth edition of the College Football Playoff Rankings was released Tuesday night with Georgia remaining the No. 1 team in the nation. The rest of the top four saw a shakeup, however, with Ohio … [+4993 chars]',
  },
  {
    source: {
      id: null,
      name: 'New York Times',
    },
    author: 'Anton Troianovski',
    title: 'Lithuania Welcomes Belarusians as It Rebuffs Middle Easterners - The New York Times',
    description: 'People seeking asylum from repression in Belarus are processed quickly and given visas. Middle Eastern migrants passing through Belarus to the E.U. face a harsher fate.',
    url: 'https://www.nytimes.com/2021/11/23/world/europe/lithuania-migrants-belarus-middle-east.html',
    urlToImage: 'https://static01.nyt.com/images/2021/11/23/world/23lithuania-migrants01/23lithuania-migrants01-facebookJumbo.jpg',
    publishedAt: '2021-11-24T01:40:12Z',
    content: 'By contrast, of the 2,639 asylum requests Lithuania processed from non-Belarusians since the start of the influx, Ms. Gudzinskaite said, only 10 were granted. Most of the arrivals came before August,… [+1214 chars]',
  },
  {
    source: {
      id: null,
      name: 'BBC News',
    },
    author: 'https://www.facebook.com/bbcnews',
    title: "PC Andrew Harper's widow wins bid to change law - BBC News",
    description: "Ministers back Lissie Harper's campaign to jail those who kill on-duty police and 999 workers for life.",
    url: 'https://www.bbc.com/news/uk-england-berkshire-59394783',
    urlToImage: 'https://ichef.bbci.co.uk/news/1024/branded_news/0039/production/_121775000_mediaitem121774999.jpg',
    publishedAt: '2021-11-24T01:37:38Z',
    content: "Image source, FamilyHandout\r\nImage caption, PC Andrew Harper married his childhood sweetheart Lissie four weeks before he was killed\r\nA campaign by PC Andrew Harper's widow to give mandatory life sen… [+3743 chars]",
  },
  {
    source: {
      id: 'axios',
      name: 'Axios',
    },
    author: 'Zachary Basu',
    title: "U.S. unveils invitation list for Biden's \"Summit for Democracy\" - Axios",
    description: 'The move is sure to infuriate China.',
    url: 'https://www.axios.com/summit-for-democracy-biden-taiwan-f9289beb-7155-4061-9f1c-459eb6e6f70a.html',
    urlToImage: 'https://images.axios.com/_yYA8B5IgwsJAMIcUfwTH4TVyUA=/0x67:6842x3916/1366x768/2021/11/24/1637716878696.jpg',
    publishedAt: '2021-11-24T01:35:20Z',
    content: "Taiwan is among the 110 delegations invited to President Biden's \"Summit for Democracy\" next month, according to a list released by the State Department on Tuesday night.\r\nWhy it matters: Taiwan's in… [+1864 chars]",
  },
  {
    source: {
      id: 'nbc-news',
      name: 'NBC News',
    },
    author: 'The Associated Press',
    title: "Italy frees man guilty of killing Amanda Knox's roommate, Meredith Kercher - NBC News",
    description: 'The only person convicted in the 2007 murder of British student Meredith Kercher was freed Tuesday after serving most of his 16-year prison sentence, his',
    url: 'https://www.nbcnews.com/news/world/italy-frees-man-guilty-killing-amanda-knoxs-roommate-meredith-kercher-rcna6564',
    urlToImage: 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2021-11/211123-Rudy-Guede-2008-ac-809p-24a3a7.jpg',
    publishedAt: '2021-11-24T01:17:00Z',
    content: 'ROME The only person convicted in the 2007 murder of British student Meredith Kercher was freed Tuesday after serving most of his 16-year prison sentence, his lawyer said.\r\nAttorney Fabrizio Ballarin… [+801 chars]',
  },
  {
    source: {
      id: 'cnn',
      name: 'CNN',
    },
    author: 'Mark Morales and Steve Almasy, CNN',
    title: 'Jury finds Unite the Right defendants liable for more than $26 million in damages - CNN',
    description: 'Unite the Right rally organizers found liable for violating Virginia conspiracy statute; plaintiffs are awarded millions in damages.',
    url: 'https://www.cnn.com/2021/11/23/us/charlottesville-unite-the-right-trial-deliberations-tuesday/index.html',
    urlToImage: 'https://cdn.cnn.com/cnnnext/dam/assets/211119011632-heather-heyer-memorial-file-super-tease.jpg',
    publishedAt: '2021-11-24T01:08:00Z',
    content: 'Charlottesville, Virginia (CNN)A jury has awarded more than $26 million in damages after finding the White nationalists who organized and participated in a violent 2017 rally here liable on a state c… [+7973 chars]',
  },
  {
    source: {
      id: null,
      name: 'New York Daily News',
    },
    author: 'Pat Leonard',
    title: 'Giants fire offensive coordinator Jason Garrett: source - New York Daily News',
    description: 'Jason Garrett is out.',
    url: 'https://www.nydailynews.com/sports/football/giants/ny-jason-garrett-fired-joe-judge-20211123-fe6x7wvgkrgvrjulsyw4omjehe-story.html',
    urlToImage: 'https://www.nydailynews.com/resizer/H49tAEHtEWl67IayYRBXYrus71M=/1200x0/top/cloudfront-us-east-1.images.arcpublishing.com/tronc/UYNZHJWKONGQRIJIQBEN4SA5NU.jpg',
    publishedAt: '2021-11-24T01:06:00Z',
    content: 'Jason Garrett is out as Giants offensive coordinator, fired on Tuesday just 26 games into a disappointingly low-scoring experiment coaching Daniel Jones.\r\nHead coach Joe Judge fired Garrett the day a… [+7596 chars]',
  },
  {
    source: {
      id: null,
      name: 'YouTube',
    },
    author: null,
    title: "Netflix's Cowboy Bebop: All the Anime Homages in the Live-Action Series - IGN",
    description: "Netflix's Cowboy Bebop series may look a lot like the original anime, but just how closely does it follow the source material? Let's take a deep dive into th...",
    url: 'https://www.youtube.com/watch?v=CHQCGvuFeus',
    urlToImage: 'https://i.ytimg.com/vi/CHQCGvuFeus/hqdefault.jpg',
    publishedAt: '2021-11-24T01:00:02Z',
    content: null,
  },
  {
    source: {
      id: 'nbc-news',
      name: 'NBC News',
    },
    author: 'Dennis Romero, Kurt Chirbas, Sara Mhaidli, Katrina Lau, Noah Frick-Alofs, Bianca Britton',
    title: "Wrestling spectator tackles WWE's Seth Rollins during live broadcast - NBC News",
    description: 'A man seen tackling pro wrestler Seth Rollins at a WWE event in New York City during a live broadcast Monday night has been accused of assault.',
    url: 'https://www.nbcnews.com/news/us-news/wrestling-spectator-tackles-wwes-seth-rollins-live-broadcast-rcna6557',
    urlToImage: 'https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1200-630,f_auto,q_auto:best/rockcms/2021-11/211123-Seth-Rollins-ew-645p-ab42e3.jpg',
    publishedAt: '2021-11-24T00:58:00Z',
    content: 'A man seen tackling pro wrestler Seth Rollins at a WWE event in New York City during a live broadcast Monday night has been accused of assault. \r\nVideo shows a man on top of Rollins, who then wiggles… [+1032 chars]',
  },
  {
    source: {
      id: null,
      name: 'FantasyPros',
    },
    author: null,
    title: 'Fantasy Football Kicker Guide and Rankings Week 12 (2021) - FantasyPros',
    description: 'Tyler Bass entered Week 11 with five games of ten or more fantasy points, including 30 combined points in Weeks 3 and 4. His worst game of the season was five points against the Dolphins in Week 2, in which ...',
    url: 'https://www.fantasypros.com/2021/11/fantasy-football-kicker-guide-and-rankings-week-12-2021/',
    urlToImage: '//cdn.fantasypros.com/wp-content/uploads/full_316323.jpg',
    publishedAt: '2021-11-24T00:53:51Z',
    content: 'Tyler Bass entered Week 11 with five games of ten or more fantasy points, including 30 combined points in Weeks 3 and 4. His worst game of the season was five points against the Dolphins in Week 2, i… [+7165 chars]',
  },
];

export default DUMMY_ARTICLES;
